export type OwnTour = {
  id?: number;
  destination: string;
  title: string;
  price: number;
  startDate?: string;
  endDate?: string;
  transport?: string;
  description?: string;
  image: string;
  photos?: string[];
  i18n?: Record<string, { destination?: string; title?: string; description?: string }>;
  sortOrder?: number;
};

export type PartnerTour = {
  hotel: string;
  destination: string;
  term: string;
  departure: string;
  nights: number;
  transport: string;
  board: string;
  price: number;
  stars: number;
  image: string;
};

export type Favorite = {
  destination: string;
  price: number;
  image: string;
};

export const heroImages = [
  "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=2200&q=80",
  "https://images.unsplash.com/photo-1520454974749-611b7248ffdb?auto=format&fit=crop&w=2200&q=80",
  "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=2200&q=80",
  "https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=2200&q=80",
];

export const defaultOwnTours: OwnTour[] = [
  {
    destination: "Santorini",
    title: "SkyTravel Signature",
    price: 12190,
    startDate: "2026-02-21",
    endDate: "2026-04-21",
    transport: "plane",
    description:
      "Romantické bílé uličky, západy slunce a pečlivě vybrané hotely v nejlepší poloze ostrova.",
    image:
      "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1200&q=80",
    photos: [
      "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?auto=format&fit=crop&w=1600&q=80",
    ],
  },
  {
    destination: "Mallorca",
    title: "SkyTravel Signature",
    price: 13550,
    startDate: "2026-02-21",
    endDate: "2026-04-21",
    transport: "plane",
    description:
      "Kombinace pláží, výletů a pohodlného ubytování s dopravou i servisem od SkyTravel.",
    image:
      "https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=1200&q=80",
    photos: [
      "https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1600&q=80",
    ],
  },
  {
    destination: "Jižní Kypr",
    title: "SkyTravel Signature",
    price: 15990,
    startDate: "2026-02-21",
    endDate: "2026-04-21",
    transport: "plane",
    description:
      "Slunce po většinu roku, čisté moře a ověřené resorty vhodné pro páry i rodiny.",
    image:
      "https://images.unsplash.com/photo-1548574505-5e239809ee19?auto=format&fit=crop&w=1200&q=80",
    photos: [
      "https://images.unsplash.com/photo-1548574505-5e239809ee19?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=80",
    ],
  },
  {
    destination: "Thajsko",
    title: "SkyTravel Signature",
    price: 26990,
    startDate: "2026-02-21",
    endDate: "2026-04-21",
    transport: "plane",
    description:
      "Exotika s kvalitními hotely, transfery a doporučenými výlety na míru vaší skupině.",
    image:
      "https://images.unsplash.com/photo-1504214208698-ea1916a2195a?auto=format&fit=crop&w=1200&q=80",
    photos: [
      "https://images.unsplash.com/photo-1504214208698-ea1916a2195a?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1600&q=80",
    ],
  },
  {
    destination: "Madagaskar",
    title: "SkyTravel Signature",
    price: 55410,
    startDate: "2026-02-21",
    endDate: "2026-04-21",
    transport: "plane",
    description:
      "Dobrodružná exotika s jedinečnou přírodou, delším pobytem a kompletní asistencí agentury.",
    image:
      "https://images.unsplash.com/photo-1518806118471-f28b20a1d79d?auto=format&fit=crop&w=1200&q=80",
    photos: [
      "https://images.unsplash.com/photo-1518806118471-f28b20a1d79d?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1521295121783-8a321d551ad2?auto=format&fit=crop&w=1600&q=80",
    ],
  },
  {
    destination: "Madeira",
    title: "SkyTravel Signature",
    price: 16490,
    startDate: "2026-02-21",
    endDate: "2026-04-21",
    transport: "plane",
    description:
      "Květinový ostrov s lehkou turistikou, oceánským výhledem a komfortním zázemím.",
    image:
      "https://images.unsplash.com/photo-1510097467424-192d713fd8b2?auto=format&fit=crop&w=1200&q=80",
    photos: [
      "https://images.unsplash.com/photo-1510097467424-192d713fd8b2?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=1600&q=80",
    ],
  },
];

export const partnerTours: PartnerTour[] = [
  {
    hotel: "King Tut Aqua Park Beach Resort",
    destination: "Egypt, Hurghada",
    term: "21.2. - 28.2.2026",
    departure: "Praha",
    nights: 8,
    transport: "letecky",
    board: "All inclusive",
    price: 8290,
    stars: 4,
    image:
      "https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?auto=format&fit=crop&w=1200&q=80",
  },
  {
    hotel: "Le Pacha Resort",
    destination: "Egypt, Hurghada",
    term: "21.2. - 28.2.2026",
    departure: "Vídeň",
    nights: 8,
    transport: "letecky",
    board: "All inclusive",
    price: 9290,
    stars: 4,
    image:
      "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&w=1200&q=80",
  },
  {
    hotel: "Beach Club Doganay",
    destination: "Turecko, Alanya",
    term: "24.2. - 2.3.2026",
    departure: "Praha",
    nights: 7,
    transport: "letecky",
    board: "All inclusive",
    price: 9580,
    stars: 5,
    image:
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
  },
  {
    hotel: "Zya Regina Resort",
    destination: "Egypt, Hurghada",
    term: "21.2. - 28.2.2026",
    departure: "Brno",
    nights: 8,
    transport: "letecky",
    board: "All inclusive",
    price: 9750,
    stars: 4,
    image:
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80",
  },
  {
    hotel: "Hawaii Suite Beach",
    destination: "Turecko, Alanya",
    term: "9.4. - 14.4.2026",
    departure: "Vídeň",
    nights: 6,
    transport: "letecky",
    board: "All inclusive",
    price: 6460,
    stars: 3,
    image:
      "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=1200&q=80",
  },
  {
    hotel: "Xperia Kandelor",
    destination: "Turecko, Alanya",
    term: "8.4. - 13.4.2026",
    departure: "Vídeň",
    nights: 6,
    transport: "letecky",
    board: "All inclusive",
    price: 6545,
    stars: 3,
    image:
      "https://images.unsplash.com/photo-1576675784201-0e142b423952?auto=format&fit=crop&w=1200&q=80",
  },
  {
    hotel: "Eva Beach",
    destination: "Turecko, Alanya",
    term: "18.4. - 23.4.2026",
    departure: "Praha",
    nights: 6,
    transport: "letecky",
    board: "All inclusive",
    price: 6600,
    stars: 3,
    image:
      "https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=1200&q=80",
  },
  {
    hotel: "Oji Beach",
    destination: "Turecko, Alanya",
    term: "8.4. - 13.4.2026",
    departure: "Vídeň",
    nights: 6,
    transport: "letecky",
    board: "All inclusive",
    price: 6615,
    stars: 3,
    image:
      "https://images.unsplash.com/photo-1520483601560-389dff434fdf?auto=format&fit=crop&w=1200&q=80",
  },
  {
    hotel: "Atlantis Paradise",
    destination: "Řecko, Rhodos",
    term: "11.5. - 18.5.2026",
    departure: "Praha",
    nights: 7,
    transport: "letecky",
    board: "All inclusive",
    price: 12880,
    stars: 4,
    image:
      "https://images.unsplash.com/photo-1530789253388-582c481c54b0?auto=format&fit=crop&w=1200&q=80",
  },
  {
    hotel: "Blue Dunes",
    destination: "Kypr, Larnaka",
    term: "5.6. - 12.6.2026",
    departure: "Praha",
    nights: 7,
    transport: "letecky",
    board: "Polopenze",
    price: 17690,
    stars: 4,
    image:
      "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1200&q=80",
  },
  {
    hotel: "Royal Palm",
    destination: "Dominikánská republika, Punta Cana",
    term: "8.7. - 18.7.2026",
    departure: "Praha",
    nights: 10,
    transport: "letecky",
    board: "All inclusive",
    price: 31290,
    stars: 5,
    image:
      "https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1200&q=80",
  },
];

export const favorites: Favorite[] = [
  {
    destination: "Bulharsko",
    price: 4893,
    image:
      "https://images.unsplash.com/photo-1473116763249-2faaef81ccda?auto=format&fit=crop&w=1200&q=80",
  },
  {
    destination: "Egypt",
    price: 8027,
    image:
      "https://images.unsplash.com/photo-1572252009286-268acec5ca0a?auto=format&fit=crop&w=1200&q=80",
  },
  {
    destination: "Tunisko",
    price: 9990,
    image:
      "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=80",
  },
  {
    destination: "Řecko",
    price: 6990,
    image:
      "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80",
  },
  {
    destination: "Turecko",
    price: 5535,
    image:
      "https://images.unsplash.com/photo-1527838832700-5059252407fa?auto=format&fit=crop&w=1200&q=80",
  },
];

export const translations = {
  cs: {
    navExclusive: "Exkluzivní nabídky",
    navPartner: "Partnerské zájezdy",
    navTop: "Top destinace",
    navServices: "Služby",
    navContact: "Kontakt",
    navAdmin: "Admin",
    heroTitle: "EXOTIKA ZA KAŽDÉHO POČASÍ",
    heroSubtitle: "SkyTravel exkluzivní nabídky + ověřené partnerské zájezdy.",
    heroBtn: "ZOBRAZIT VÍCE",
    searchWhere: "Kam pojedeme",
    searchPlaceholder: "Místo nebo hotel",
    searchDate: "Odjezd od / návrat do",
    searchTransport: "Doprava",
    searchPeople: "Skladba osob",
    searchBtn: "VYHLEDAT",
    searchAdults: "Dospělí",
    searchChildren: "Dětí",
    searchDone: "Hotovo",
    searchDeparture: "Odjezd od",
    searchReturn: "Návrat do",
    transportAny: "Nerozhoduje",
    transportFlight: "Letecky",
    transportBus: "Autobus",
    transportOwn: "Vlastní doprava",
    adminTitle: "Admin panel nabídek",
    editOwn: "Editace exkluzivních nabídek",
    editNote: "Změny se ihned projeví na hlavní stránce v sekci exkluzivních nabídek.",
    labelDestination: "Destinace",
    labelBadge: "Badge text",
    labelPrice: "Cena od (Kč)",
    labelImage: "URL obrázku",
    save: "Uložit nabídku",
    new: "Nová",
    listOwn: "Vaše SkyTravel nabídky",
    apiReadonly: "Partnerské zájezdy (API, pouze pro čtení)",
    apiNote: "Tyto položky spravuje partner přes API. V adminu je nelze upravovat.",
    
    // Transports
    plane: "Letecky",
    train: "Vlakem",
    bus: "Autobusem",
    car: "Vlastní doprava",
    boat: "Lodí",
    transportOffer: "Dle nabídky",

    // Modals
    modalTypeOwn: "Exkluzivní nabídka",
    modalDescOwn: "Exkluzivní nabídka SkyTravel s ověřenými službami a asistencí agentury.",
    modalTypePartner: "Partnerský zájezd",
    modalDescPartner: "Detail poskytnutý partnerem přes API feed.",
    modalTypeFav: "Destinace",
    modalDescFav: "Přehled oblíbené destinace a orientačních cen.",
    modalLoc: "Lokalita",
    modalTerm: "Termín",
    modalTransportTop: "Doprava",
    modalPriceFrom: "Cena od",
    from: "od",
    nights: "nocí",

    modalEmailLabel: "Zanechte e-mail pro poptávku SkyTravel",
    modalEmailPlaceholder: "vas@email.cz",
    modalConsentNews: "Souhlasím se zasíláním novinek a nabídek SkyTravel.",
    modalConsentGdpr: "Souhlasím se zpracováním",
    modalGdprLink: "osobních údajů",
    modalSubmit: "ODESLAT POPTÁVKU",
    modalSuccess: "Děkujeme. Požadavek byl odeslán na info@skytravel.cz z e-mailu",
    modalError: "Odeslání se nepodařilo, zkuste to prosím znovu.",

    // Sections
    sectionOwnTitle: "VYBRALI JSME PRO VÁS",
    sectionOwnSub: "Exkluzivní nabídky SkyTravel",
    sectionTodayTitle: "DNES VÁM NABÍZÍME",
    sectionToday1: "Pečlivý výběr",
    sectionToday1b: "vlastních nabídek",
    sectionToday2: "1000+",
    sectionToday2b: "partnerských zájezdů",
    sectionTodayNote: "SkyTravel roste - vlastní portfolio je priorita.",
    sectionLastMinute: "LAST MINUTE DOVOLENÁ",
    
    sectionAllIncTitle: "LETECKÁ DOVOLENÁ S ALL INCLUSIVE",
    budget1: "do 10 000 Kč",
    budget2: "10 000 - 15 000 Kč",
    budget3: "15 000 - 20 000 Kč",
    budget4: "20 000+ Kč",
    emptyState: "Pro tento filtr nejsou dostupné žádné nabídky.",
    
    sectionFavTitle: "OBLÍBENÉ DESTINACE",
    
    sectionSocialTitle: "NENECHTE SI NIC UJÍT",
    sectionSocialSub: "Sledujte SkyTravel na sociálních sítích.",
    polaroid1: "SkyTravel trip",
    polaroid2: "Vlastní zážitky",

    // Footer
    footerSec1: "EXKLUZIVNÍ NABÍDKY",
    f1_1: "Pevné termíny",
    f1_2: "Ověřené hotely",
    f1_3: "Menší skupiny",
    f1_4: "CZ podpora na místě",
    
    footerSec2: "PARTNERSKÉ ZÁJEZDY",
    f2_1: "Výběr z více CK",
    f2_2: "Legální prodej zájezdů",
    f2_3: "Rychlé srovnání cen",
    f2_4: "Filtrace dle rozpočtu",
    
    footerSec3: "SERVIS PRO KLIENTY",
    f3_1: "Cestovní pojištění",
    f3_2: "Převod rezervace",
    f3_3: "Storno podmínky",
    f3_4: "Časté dotazy (FAQ)",
    
    footerSec4: "SKYTRAVEL",
    f4_1: "O nás",
    f4_2: "Reference klientů",
    f4_3: "Spolupráce s agenturami",
    f4_4: "Kontakt",

    footerCity: "PRAHA",
    footerHours: "Po-Pá 9:00-17:00",
    footerContact: "KONTAKT",
    footerNewsTitle: "ZASÍLÁNÍ NOVINEK",
    footerNewsBtn: "ODESLAT",
    footerTerms: "Obchodní podmínky",
    footerGdpr: "Ochrana osobních údajů",

    // Lead Popup
    leadBadge: "Exkluzivní nabídky",
    leadTitle: "Získejte bonusový travel guide",
    leadDesc: "Pošleme vám exkluzivní nabídky SkyTravel a navíc bonusový travel guide sheet. Stačí e-mail.",
    leadConsentNews: "Souhlasím se zasíláním marketingových nabídek.",
    leadSubmit: "Chci nabídky",
    leadSuccess: "Díky! Potvrzení a guide pošleme na",
    // Cookies
    cookieTitle: "Cookies",
    cookieText: "Kliknutím na „Přijmout všechny cookies“ souhlasíte s ukládáním cookies na vašem zařízení pro zlepšení navigace, analýzu návštěvnosti a podporu marketingu.",
    cookieManage: "Spravovat cookies",
    cookieAccept: "Přijmout všechny cookies",
    cookieReject: "Odmítnout vše",
    cookieSettingsTitle: "Nastavení cookies",
    cookieSettingsIntro: "Cookies používáme pro základní funkce webu, měření návštěvnosti a personalizaci nabídky. Můžete si upravit, které cookies povolíte.",
    cookieSave: "Potvrdit volby",
    cookieAllowAll: "Povolit všechny cookies",
    cookieNecessary: "Nezbytné cookies",
    cookieAnalytics: "Analytické cookies",
    cookieMarketing: "Marketingové cookies",
    cookieNecessaryDesc: "Nezbytné pro fungování webu. Vždy aktivní.",
    cookieAnalyticsDesc: "Pomáhají měřit výkon webu a zlepšovat služby.",
    cookieMarketingDesc: "Umožňují zobrazovat relevantní nabídky a kampaně.",
  },
  en: {
    navExclusive: "Exclusive offers",
    navPartner: "Partner tours",
    navTop: "Top destinations",
    navServices: "Services",
    navContact: "Contact",
    navAdmin: "Admin",
    heroTitle: "EXOTIC TRAVEL IN ANY WEATHER",
    heroSubtitle: "SkyTravel exclusive offers + verified partner tours.",
    heroBtn: "SHOW MORE",
    searchWhere: "Where to",
    searchPlaceholder: "Destination or hotel",
    searchDate: "Departure / Return",
    searchTransport: "Transport",
    searchPeople: "Travelers",
    searchBtn: "SEARCH",
    searchAdults: "Adults",
    searchChildren: "Children",
    searchDone: "Done",
    searchDeparture: "Departure",
    searchReturn: "Return",
    transportAny: "Any",
    transportFlight: "Flight",
    transportBus: "Bus",
    transportOwn: "Own transport",
    adminTitle: "Offers admin panel",
    editOwn: "Edit exclusive offers",
    editNote: "Changes are reflected instantly on the homepage exclusive section.",
    labelDestination: "Destination",
    labelBadge: "Badge text",
    labelPrice: "Price from (CZK)",
    labelImage: "Image URL",
    save: "Save offer",
    new: "New",
    listOwn: "Your SkyTravel offers",
    apiReadonly: "Partner tours (API, read-only)",
    apiNote: "These items are managed by partner API and cannot be edited here.",

    // Transports
    plane: "By plane",
    train: "By train",
    bus: "By bus",
    car: "Own transport",
    boat: "By boat",
    transportOffer: "As offered",

    // Modals
    modalTypeOwn: "Exclusive offer",
    modalDescOwn: "SkyTravel exclusive offer with verified services and agency assistance.",
    modalTypePartner: "Partner tour",
    modalDescPartner: "Detail provided by partner via API feed.",
    modalTypeFav: "Destination",
    modalDescFav: "Overview of popular destination and estimated prices.",
    modalLoc: "Location",
    modalTerm: "Term",
    modalTransportTop: "Transport",
    modalPriceFrom: "Price from",
    from: "from",
    nights: "nights",

    modalEmailLabel: "Leave an email for SkyTravel inquiry",
    modalEmailPlaceholder: "your@email.com",
    modalConsentNews: "I agree to receive SkyTravel news and offers.",
    modalConsentGdpr: "I agree to the processing of",
    modalGdprLink: "personal data",
    modalSubmit: "SEND INQUIRY",
    modalSuccess: "Thank you. The request has been sent to info@skytravel.cz from",
    modalError: "Submission failed, please try again.",

    // Sections
    sectionOwnTitle: "WE CHOSE FOR YOU",
    sectionOwnSub: "SkyTravel Exclusive Offers",
    sectionTodayTitle: "TODAY WE OFFER",
    sectionToday1: "Careful selection",
    sectionToday1b: "of exclusive offers",
    sectionToday2: "1000+",
    sectionToday2b: "partner tours",
    sectionTodayNote: "SkyTravel is growing - our own portfolio is a priority.",
    sectionLastMinute: "LAST MINUTE HOLIDAYS",
    
    sectionAllIncTitle: "FLIGHT HOLIDAYS WITH ALL INCLUSIVE",
    budget1: "up to 10 000 CZK",
    budget2: "10 000 - 15 000 CZK",
    budget3: "15 000 - 20 000 CZK",
    budget4: "20 000+ CZK",
    emptyState: "No offers available for this filter.",
    
    sectionFavTitle: "POPULAR DESTINATIONS",
    
    sectionSocialTitle: "DON'T MISS ANYTHING",
    sectionSocialSub: "Follow SkyTravel on social media.",
    polaroid1: "SkyTravel trip",
    polaroid2: "Own experiences",

    // Footer
    footerSec1: "EXCLUSIVE OFFERS",
    f1_1: "Fixed dates",
    f1_2: "Verified hotels",
    f1_3: "Smaller groups",
    f1_4: "Local EN/CZ support",
    
    footerSec2: "PARTNER TOURS",
    f2_1: "Choice from multiple agencies",
    f2_2: "Legal tour sales",
    f2_3: "Quick price comparison",
    f2_4: "Budget filter",
    
    footerSec3: "CLIENT SERVICE",
    f3_1: "Travel insurance",
    f3_2: "Booking transfer",
    f3_3: "Cancellation policy",
    f3_4: "FAQ",
    
    footerSec4: "SKYTRAVEL",
    f4_1: "About us",
    f4_2: "Client references",
    f4_3: "Agency cooperation",
    f4_4: "Contact",

    footerCity: "PRAGUE",
    footerHours: "Mon-Fri 9:00-17:00",
    footerContact: "CONTACT",
    footerNewsTitle: "NEWSLETTER",
    footerNewsBtn: "SEND",
    footerTerms: "Terms and Conditions",
    footerGdpr: "Privacy Policy",

    // Lead Popup
    leadBadge: "Exclusive offers",
    leadTitle: "Get a bonus travel guide",
    leadDesc: "We will send you SkyTravel exclusive offers plus a bonus travel guide sheet. Just an email.",
    leadConsentNews: "I agree to receive marketing offers.",
    leadSubmit: "I want offers",
    leadSuccess: "Thanks! We will send the guide to",
    // Cookies
    cookieTitle: "Cookies",
    cookieText: "By clicking “Accept all cookies”, you agree to the storage of cookies on your device to enhance site navigation, analyze usage, and support marketing.",
    cookieManage: "Manage cookies",
    cookieAccept: "Accept all cookies",
    cookieReject: "Reject all",
    cookieSettingsTitle: "Cookies settings",
    cookieSettingsIntro: "We use cookies for core functionality, analytics, and personalization. You can customize which cookies to allow.",
    cookieSave: "Confirm my choices",
    cookieAllowAll: "Allow all cookies",
    cookieNecessary: "Essential cookies",
    cookieAnalytics: "Analytics / performance cookies",
    cookieMarketing: "Marketing cookies",
    cookieNecessaryDesc: "Required for basic site functionality. Always active.",
    cookieAnalyticsDesc: "Help us measure traffic and improve performance.",
    cookieMarketingDesc: "Used to show relevant offers and campaigns.",
  },
  uk: {
    navExclusive: "Ексклюзивні пропозиції",
    navPartner: "Партнерські тури",
    navTop: "Топ напрямки",
    navServices: "Послуги",
    navContact: "Контакт",
    navAdmin: "Адмін",
    heroTitle: "ЕКЗОТИКА ЗА БУДЬ-ЯКОЇ ПОГОДИ",
    heroSubtitle: "Ексклюзивні пропозиції SkyTravel + перевірені партнерські тури.",
    heroBtn: "ДИВИТИСЯ БІЛЬШЕ",
    searchWhere: "Куди їдемо",
    searchPlaceholder: "Місце або готель",
    searchDate: "Виїзд / Повернення",
    searchTransport: "Транспорт",
    searchPeople: "Склад туристів",
    searchBtn: "ПОШУК",
    searchAdults: "Дорослі",
    searchChildren: "Діти",
    searchDone: "Готово",
    searchDeparture: "Виїзд",
    searchReturn: "Повернення",
    transportAny: "Будь-який",
    transportFlight: "Літаком",
    transportBus: "Автобус",
    transportOwn: "Власний транспорт",
    adminTitle: "Адмін-панель пропозицій",
    editOwn: "Редагування ексклюзивних пропозицій",
    editNote: "Зміни одразу з'являться на головній сторінці.",
    labelDestination: "Напрямок",
    labelBadge: "Текст бейджа",
    labelPrice: "Ціна від (Kč)",
    labelImage: "URL зображення",
    save: "Зберегти",
    new: "Нова",
    listOwn: "Ваші пропозиції SkyTravel",
    apiReadonly: "Партнерські тури (API, лише читання)",
    apiNote: "Ці позиції керуються API партнера і тут не редагуються.",

    // Transports
    plane: "Літаком",
    train: "Поїздом",
    bus: "Автобусом",
    car: "Власний транспорт",
    boat: "Човном",
    transportOffer: "За пропозицією",

    // Modals
    modalTypeOwn: "Ексклюзивна пропозиція",
    modalDescOwn: "Ексклюзивна пропозиція SkyTravel з перевіреними послугами та підтримкою агентства.",
    modalTypePartner: "Партнерський тур",
    modalDescPartner: "Деталі надані партнером через API feed.",
    modalTypeFav: "Напрямок",
    modalDescFav: "Огляд популярного напрямку та орієнтовних цін.",
    modalLoc: "Локація",
    modalTerm: "Термін",
    modalTransportTop: "Транспорт",
    modalPriceFrom: "Ціна від",
    from: "від",
    nights: "ночей",

    modalEmailLabel: "Залиште e-mail для запиту до SkyTravel",
    modalEmailPlaceholder: "vas@email.com",
    modalConsentNews: "Я згоден отримувати новини та пропозиції SkyTravel.",
    modalConsentGdpr: "Я згоден на обробку",
    modalGdprLink: "персональних даних",
    modalSubmit: "ВІДПРАВИТИ ЗАПИТ",
    modalSuccess: "Дякуємо. Ваш запит відправлено на info@skytravel.cz з e-mail",
    modalError: "Відправка не вдалася, будь ласка, спробуйте ще раз.",

    // Sections
    sectionOwnTitle: "МИ ОБРАЛИ ДЛЯ ВАС",
    sectionOwnSub: "Ексклюзивні пропозиції SkyTravel",
    sectionTodayTitle: "СЬОГОДНІ ПРОПОНУЄМО",
    sectionToday1: "Ретельний вибір",
    sectionToday1b: "власних пропозицій",
    sectionToday2: "1000+",
    sectionToday2b: "партнерських турів",
    sectionTodayNote: "SkyTravel росте - власне портфоліо є пріоритетом.",
    sectionLastMinute: "LAST MINUTE ВІДПОЧИНОК",
    
    sectionAllIncTitle: "АВІАТУРИ З ALL INCLUSIVE",
    budget1: "до 10 000 Kč",
    budget2: "10 000 - 15 000 Kč",
    budget3: "15 000 - 20 000 Kč",
    budget4: "20 000+ Kč",
    emptyState: "Для цього фільтра немає доступних пропозицій.",
    
    sectionFavTitle: "ПОПУЛЯРНІ НАПРЯМКИ",
    
    sectionSocialTitle: "НЕ ПРОПУСТІТЬ НІЧОГО",
    sectionSocialSub: "Слідкуйте за SkyTravel у соціальних мережах.",
    polaroid1: "Подорож SkyTravel",
    polaroid2: "Власні враження",

    // Footer
    footerSec1: "ЕКСКЛЮЗИВНІ ПРОПОЗИЦІЇ",
    f1_1: "Фіксовані дати",
    f1_2: "Перевірені готелі",
    f1_3: "Невеликі групи",
    f1_4: "CZ/UK підтримка на місці",
    
    footerSec2: "ПАРТНЕРСЬКІ ТУРИ",
    f2_1: "Вибір з багатьох агенцій",
    f2_2: "Легальний продаж турів",
    f2_3: "Швидке порівняння цін",
    f2_4: "Фільтр за бюджетом",
    
    footerSec3: "СЕРВІС ДЛЯ КЛІЄНТІВ",
    f3_1: "Туристичне страхування",
    f3_2: "Передача бронювання",
    f3_3: "Умови ануляції",
    f3_4: "Часті питання (FAQ)",
    
    footerSec4: "SKYTRAVEL",
    f4_1: "Про нас",
    f4_2: "Відгуки клієнтів",
    f4_3: "Співпраця з агенціями",
    f4_4: "Контакт",

    footerCity: "ПРАГА",
    footerHours: "Пн-Пт 9:00-17:00",
    footerContact: "КОНТАКТ",
    footerNewsTitle: "ПІДПИСКА НА НОВИНИ",
    footerNewsBtn: "ВІДПРАВИТИ",
    footerTerms: "Комерційні умови",
    footerGdpr: "Захист персональних даних",

    // Lead Popup
    leadBadge: "Ексклюзивні пропозиції",
    leadTitle: "Отримайте бонусний travel guide",
    leadDesc: "Ми надішлемо вам ексклюзивні пропозиції SkyTravel плюс бонусний путівник. Потрібен лише e-mail.",
    leadConsentNews: "Я згоден отримувати маркетингові пропозиції.",
    leadSubmit: "Хочу пропозиції",
    leadSuccess: "Дякуємо! Ми відправимо guide на",
    // Cookies
    cookieTitle: "Cookies",
    cookieText: "Натискаючи «Прийняти всі файли cookie», ви погоджуєтеся на зберігання файлів cookie на вашому пристрої для покращення навігації сайтом, аналізу використання та підтримки маркетингу.",
    cookieManage: "Керувати файлами cookie",
    cookieAccept: "Прийняти всі",
    cookieReject: "Відхилити всі",
    cookieSettingsTitle: "Налаштування cookie",
    cookieSettingsIntro: "Ми використовуємо файли cookie для основної роботи, аналітики та персоналізації. Ви можете налаштувати свої файли cookie.",
    cookieSave: "Підтвердити вибір",
    cookieAllowAll: "Дозволити всі",
    cookieNecessary: "Необхідні cookie",
    cookieAnalytics: "Аналітичні cookie",
    cookieMarketing: "Маркетингові cookie",
    cookieNecessaryDesc: "Необхідні для базової роботи сайту. Завжди активні.",
    cookieAnalyticsDesc: "Допомагають вимірювати трафік та покращувати роботу.",
    cookieMarketingDesc: "Використовуються для показу відповідних пропозицій.",
  },
  ru: {
    navExclusive: "Эксклюзивные предложения",
    navPartner: "Партнерские туры",
    navTop: "Топ направления",
    navServices: "Услуги",
    navContact: "Контакт",
    navAdmin: "Админ",
    heroTitle: "ЭКЗОТИКА ПРИ ЛЮБОЙ ПОГОДЕ",
    heroSubtitle: "Эксклюзивные предложения SkyTravel + проверенные партнерские туры.",
    heroBtn: "ПОКАЗАТЬ БОЛЬШЕ",
    searchWhere: "Куда поедем",
    searchPlaceholder: "Место или отель",
    searchDate: "Выезд / Возврат",
    searchTransport: "Транспорт",
    searchPeople: "Состав туристов",
    searchBtn: "ПОИСК",
    searchAdults: "Взрослые",
    searchChildren: "Дети",
    searchDone: "Готово",
    searchDeparture: "Выезд",
    searchReturn: "Возврат",
    transportAny: "Любой",
    transportFlight: "Самолет",
    transportBus: "Автобус",
    transportOwn: "Свой транспорт",
    adminTitle: "Админ-панель предложений",
    editOwn: "Редактирование эксклюзивных предложений",
    editNote: "Изменения сразу отображаются на главной странице.",
    labelDestination: "Направление",
    labelBadge: "Текст бейджа",
    labelPrice: "Цена от (Kč)",
    labelImage: "URL изображения",
    save: "Сохранить",
    new: "Новая",
    listOwn: "Ваши предложения SkyTravel",
    apiReadonly: "Партнерские туры (API, только чтение)",
    apiNote: "Эти позиции управляются API партнера и не редактируются здесь.",

    // Transports
    plane: "Самолетом",
    train: "Поездом",
    bus: "Автобусом",
    car: "Свой транспорт",
    boat: "На лодке",
    transportOffer: "По предложению",

    // Modals
    modalTypeOwn: "Эксклюзивное предложение",
    modalDescOwn: "Эксклюзивное предложение SkyTravel с проверенными услугами и поддержкой агентства.",
    modalTypePartner: "Партнерский тур",
    modalDescPartner: "Детали предоставлены партнером через API feed.",
    modalTypeFav: "Направление",
    modalDescFav: "Обзор популярного направления и ориентировочных цен.",
    modalLoc: "Локация",
    modalTerm: "Срок",
    modalTransportTop: "Транспорт",
    modalPriceFrom: "Цена от",
    from: "от",
    nights: "ночей",

    modalEmailLabel: "Оставьте e-mail для запроса в SkyTravel",
    modalEmailPlaceholder: "vas@email.com",
    modalConsentNews: "Я согласен получать новости и предложения SkyTravel.",
    modalConsentGdpr: "Я согласен на обработку",
    modalGdprLink: "персональных данных",
    modalSubmit: "ОТПРАВИТЬ ЗАПРОС",
    modalSuccess: "Спасибо. Ваш запрос отправлен на info@skytravel.cz с e-mail",
    modalError: "Отправка не удалась, пожалуйста, попробуйте еще раз.",

    // Sections
    sectionOwnTitle: "МЫ ВЫБРАЛИ ДЛЯ ВАС",
    sectionOwnSub: "Эксклюзивные предложения SkyTravel",
    sectionTodayTitle: "СЕГОДНЯ ПРЕДЛАГАЕМ",
    sectionToday1: "Тщательный выбор",
    sectionToday1b: "собственных предложений",
    sectionToday2: "1000+",
    sectionToday2b: "партнерских туров",
    sectionTodayNote: "SkyTravel растет - собственное портфолио в приоритете.",
    sectionLastMinute: "LAST MINUTE ОТДЫХ",
    
    sectionAllIncTitle: "АВИАТУРЫ С ALL INCLUSIVE",
    budget1: "до 10 000 Kč",
    budget2: "10 000 - 15 000 Kč",
    budget3: "15 000 - 20 000 Kč",
    budget4: "20 000+ Kč",
    emptyState: "Для этого фильтра нет доступных предложений.",
    
    sectionFavTitle: "ПОПУЛЯРНЫЕ НАПРАВЛЕНИЯ",
    
    sectionSocialTitle: "НЕ ПРОПУСТИТЕ НИЧЕГО",
    sectionSocialSub: "Следите за SkyTravel в социальных сетях.",
    polaroid1: "Поездка SkyTravel",
    polaroid2: "Собственные впечатления",

    // Footer
    footerSec1: "ЭКСКЛЮЗИВНЫЕ ПРЕДЛОЖЕНИЯ",
    f1_1: "Фиксированные даты",
    f1_2: "Проверенные отели",
    f1_3: "Небольшие группы",
    f1_4: "CZ/RU поддержка на месте",
    
    footerSec2: "ПАРТНЕРСКИЕ ТУРЫ",
    f2_1: "Выбор из многих агентств",
    f2_2: "Легальная продажа туров",
    f2_3: "Быстрое сравнение цен",
    f2_4: "Фильтр по бюджету",
    
    footerSec3: "СЕРВИС ДЛЯ КЛИЕНТОВ",
    f3_1: "Туристическое страхование",
    f3_2: "Передача бронирования",
    f3_3: "Условия аннуляции",
    f3_4: "Частые вопросы (FAQ)",
    
    footerSec4: "SKYTRAVEL",
    f4_1: "О нас",
    f4_2: "Отзывы клиентов",
    f4_3: "Сотрудничество с агентствами",
    f4_4: "Контакт",

    footerCity: "ПРАГА",
    footerHours: "Пн-Пт 9:00-17:00",
    footerContact: "КОНТАКТ",
    footerNewsTitle: "ПОДПИСКА НА НОВОСТИ",
    footerNewsBtn: "ОТПРАВИТЬ",
    footerTerms: "Коммерческие условия",
    footerGdpr: "Защита персональных данных",

    // Lead Popup
    leadBadge: "Эксклюзивные предложения",
    leadTitle: "Получите бонусный travel guide",
    leadDesc: "Мы вышлем вам эксклюзивные предложения SkyTravel плюс бонусный путеводитель. Нужен только e-mail.",
    leadConsentNews: "Я согласен получать маркетинговые предложения.",
    leadSubmit: "Хочу предложения",
    leadSuccess: "Спасибо! Мы отправим guide на",
    // Cookies
    cookieTitle: "Cookies",
    cookieText: "Нажимая «Принять все файлы cookie», вы соглашаетесь на хранение файлов cookie на вашем устройстве для улучшения навигации по сайту, анализа использования и поддержки маркетинга.",
    cookieManage: "Управлять cookie",
    cookieAccept: "Принять все",
    cookieReject: "Отклонить все",
    cookieSettingsTitle: "Настройки cookie",
    cookieSettingsIntro: "Мы используем файлы cookie для основной функциональности, аналитики и персонализации. Вы можете настроить файлы cookie.",
    cookieSave: "Подтвердить выбор",
    cookieAllowAll: "Разрешить все",
    cookieNecessary: "Необходимые cookie",
    cookieAnalytics: "Аналитические cookie",
    cookieMarketing: "Маркетинговые cookie",
    cookieNecessaryDesc: "Необходимы для работы сайта. Всегда активны.",
    cookieAnalyticsDesc: "Помогают измерять трафик и улучшать работу.",
    cookieMarketingDesc: "Используются для показа релевантных предложений.",
  },
};
